-- 内置账户
INSERT INTO SF_USER (ID, USER_NAME, PASSWORD, NAME, CREATE_TIME)
VALUES ('10001', 'admin', 'admin', '管理员', '2022.11.23 13:36');

-- 测试数据
INSERT INTO SF_DEVICE_GROUP (ID, LABEL, NAME)
VALUES ('10001', '搅拌桩', 'JBZ');